[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
# World Chain Networks (using environment variables for security)
worldchain_sepolia = "https://worldchain-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
worldchain_mainnet = "https://worldchain-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

# Ethereum Networks (for comparison/fallback)
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

# Note: Etherscan verification is optional - you can skip it if you don't have API keys
# [etherscan]
# worldchain_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://worldchain-sepolia.explorer.alchemy.com/api" }
# worldchain_mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://worldscan.org/api" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
